Atractorrr/Attraction-FE

.github/workflows/workflow.yml, package.json, pnpm-lock.yaml
- [ATR-40 레포지토리 세팅](https://attractorr.atlassian.net/browse/ATR-40)
- [ATR-42 Github action CI 구현](https://attractorr.atlassian.net/browse/ATR-40)
<br/>
- type 커맨드 비활성화
<br/>
=> Github Action type 커맨드 비활성화

package.json, packages/config/package.json, packages/design-system/package.json, packages/icons/package.json
<br/>
-[package.json lint 커맨드 변경](https://attractorr.atlassian.net/browse/ATR-74)
<br/>
- lint 커맨드 변경
<br/>
=> package.json lint 커맨드 수정

.eslintrc.cjs, .github/workflows/workflow.yml, apps/service/.eslintrc.cjs, apps/service/__mocks__/handlers/inbox/index.ts, apps/service/__mocks__/handlers/main/index.ts, apps/service/entities/article/model/type/article.ts, apps/service/entities/article/ui/CardItem.tsx, apps/service/entities/news-card/ui/NewsCard.tsx, apps/service/entities/profile/lib/util/getCategorySVG.ts, apps/service/entities/profile/ui/PreferTagItem.tsx, apps/service/features/filter-article/model/useCategory.ts, apps/service/features/filter-article/ui/FilterDropdownBtn.tsx, apps/service/features/filter-article/ui/SearchBar.tsx, apps/service/features/profile-container/ui/ProfileContainer.tsx, apps/service/features/subscribe-list/ui/SubscribeList.tsx, apps/service/package.json, apps/service/widgets/recent-articles-container/ui/RecentArticlesContainer.tsx, apps/service/widgets/trend-newsletters/ui/TrendNewsletters.tsx, package.json
<br/>
- [코드 컨벤션 일치](https://attractorr.atlassian.net/browse/ATR-95)
<br/>
- next lint 커맨드가 검사하지 않는 부분들이 있어 lint 스크립트를 수정
- lint 에러가 발생하는 부분들을 모두 수정
- CI에 type 커맨드를 추가하여 CI시 타입 체킹 작동
**현재 import/order 규칙이 eslint cli상에서는 작동하나 IDE상에서는 해당 에러가 보여지지 않아 해당 부분 확인 후 수정 예정입니다**
<br/>
=> 린트 커맨드 변경 및 로직 수정

apps/service/.eslintrc.cjs, apps/service/.lintstagedrc.json, apps/service/__mocks__/handlers/main/index.ts, apps/service/app/page.tsx, apps/service/entities/trend-newsletters/model/type/trendNewsletter.ts, apps/service/entities/trend-newsletters/ui/TrendNewsletterItem.tsx, apps/service/features/newsletter-categories/api/fetchPreferCategories.ts, apps/service/features/newsletter-categories/api/index.ts, apps/service/features/newsletter-categories/index.ts, apps/service/features/newsletter-categories/lib/util/getSortedCategories.ts, apps/service/features/newsletter-categories/model/index.ts, apps/service/features/newsletter-categories/model/type/index.ts, apps/service/features/newsletter-categories/model/type/preferCaterories.ts, apps/service/features/newsletter-categories/ui/NewsletterCategories.tsx, apps/service/package.json, apps/service/shared/ui/title/Title.tsx, apps/service/widgets/recent-articles-container/ui/RecentArticlesContainer.tsx, apps/service/widgets/trend-newsletters/ui/TrendNewsletters.tsx, apps/service/widgets/user-rank/ui/UserRank.tsx, package.json, packages/design-system/.lintstagedrc.json, packages/design-system/package.json, packages/icons/.lintstagedrc.json, packages/icons/package.json, pnpm-lock.yaml
<br/>
- [1차 배포전 API 사양에 맞추어 최종점검](https://attractorr.atlassian.net/jira/software/projects/ATR/issues/ATR-183?jql=project%20%3D%20%22ATR%22%20ORDER%20BY%20created%20DESC)
<br/>
- 카테고리 선택시 트렌드 뉴스레터 섹션이 전체 리렌더링되는 문제 수정
- 1차 배포 전 API 변경에 따른 내용 반영
- lint-staged가 각 모듈별로 실행되도록 변경
- 디자인 시안에 맞추어 항목 수정
<br/>
=> 1차 배포 전 메인페이지 최종 수정

apps/service/entities/news-card/ui/CardThumbnail.tsx, apps/service/entities/profile/ui/PreferTagItem.tsx, apps/service/features/calendar/ui/Calendar.tsx, apps/service/features/graph/ui/Graph.tsx, apps/service/features/profile-container/ui/ProfileContainer.tsx, apps/service/features/recent-newsletter/ui/RecentNewsletterContainer.tsx, apps/service/features/subscribe-list/ui/SubscribeList.tsx, apps/service/shared/ui/content/ui/ContentContainer.tsx, apps/service/shared/ui/content/ui/ContentTitle.tsx, apps/service/widgets/user-record/ui/UserRecord.tsx
- [x ] Refactoring (no functional changes, no api changes)
<br/>
-
<br/>
- 마이페이지 반응형 레이아웃 수정
- 마이페이지 다크 테마 적용
=> feat: 다크테마 적용 및 마이페이지 반응형 수정 (#ATR-187)

apps/service/app/layout.tsx, apps/service/entities/auth/constant/index.ts, apps/service/entities/auth/constant/path.ts, apps/service/entities/auth/index.ts, apps/service/middleware.ts, apps/service/shared/ui/carousel/Carousel.tsx, apps/service/widgets/sign-in/ui/SignIn.tsx
<br/>
- [[FE] 위젯 추가 및 스타일링](https://attractorr.atlassian.net/browse/ATR-175)
<br/>
- public path에서 sidebar, header, footer가 보이지 않도록 수정
- 무분별한 section 태그 div로 전환
<br/>
=> public path, private path 적용

apps/service/app/layout.tsx, apps/service/app/sign-in/page.tsx, apps/service/app/sign-up/page.tsx, apps/service/app/widget.tsx, apps/service/widgets/header/ui/Header.tsx, apps/service/widgets/sign-in/ui/SignIn.tsx
=> 1차 배포 전 검수 및 병합

apps/service/__mocks__/handlers/main/index.ts, apps/service/entities/trend-newsletters/model/type/trendNewsletter.ts, apps/service/entities/trend-newsletters/ui/TrendNewsletterList.tsx, apps/service/widgets/trend-newsletters/ui/TrendNewsletters.tsx
<br/>
-
<br/>
- trendNewsletter api 변경사항 적용
<br/>
=> trendNewsletter api 변경사항 적용

apps/service/app/sign-up/page.tsx, apps/service/entities/user-setting/ui/UserSettingList.tsx, apps/service/features/sign-up/ui/UserAgreement.tsx, apps/service/features/sign-up/ui/UserInfoExpirationDate.tsx, apps/service/features/sign-up/ui/UserInfoField.tsx, apps/service/features/sign-up/ui/UserJobField.tsx, apps/service/features/sign-up/ui/UserPreferTagField.tsx, apps/service/widgets/sign-up-container/ui/SignUp.tsx
- 회원가입 다크테마 적용
- 회원가입 레이아웃 반응형 리팩토링
<br/>
=> 회원가입 다크테마 수정 및 변경 레이아웃 적용 

apps/service/__mocks__/handlers/main/index.ts, apps/service/app/api/auth/callback/google/route.ts, apps/service/app/page.tsx, apps/service/entities/recent-article-item/ui/RecentArticleItem.tsx, apps/service/entities/trend-newsletters/ui/TrendNewsletterItem.tsx, apps/service/entities/trend-newsletters/ui/TrendNewsletterList.tsx, apps/service/features/recent-articles/api/fetchArticles.ts, apps/service/features/recent-articles/model/useRecentArticles.ts, apps/service/next.config.mjs, apps/service/widgets/recent-articles-container/ui/RecentArticlesContainer.tsx
=> 백엔드 배포 반영 (1)

apps/service/entities/user-article/api/getUserCategories.ts, apps/service/features/filter-article/ui/CategoryDropdownBtn.tsx
<br/>
- [api 관련 로직 에러 처리](https://attractorr.atlassian.net/browse/ATR-238)
<br/>
- 유저 카테고리 및 아티클 api 연동 (1차 배포 때 누락된 api)
<br/>
=> 유저 카테고리 및 아티클 api 연동

apps/service/app/api/auth/register-success/route.ts, apps/service/widgets/sign-up-container/ui/SignUp.tsx
<br/>
- 회원가입시 쿠키 삭제 (https://attractorr.atlassian.net/browse/ATR-147)
<br/>
- 회원가입시 쿠키 삭제
=> refactor: 로그인 시 쿠키 삭제 구현 (#ATR-147)

apps/service/app/api/auth/register-success/route.ts
<br/>
- next response 추가
<br/>
- next response 
<br/>
-
<br/>
=> refactor: next response 수정 (#ATR-147)

apps/service/widgets/sign-up-container/ui/SignUp.tsx
<br/>
-
<br/>
- api router 경로 수정
=> api router 경로 수정 

apps/service/features/sign-up/ui/UserInfoNicknameInput.tsx
<br/>
-
<br/>
- 인풋 글자 수 제한 기능 추가
<br/>
-
<br/>
=> 인풋 글자제한 기능 

apps/service/features/profile-container/ui/ProfileSettingModal.tsx
<br/>
-(백그라운드 url)[https://attractorr.atlassian.net/browse/ATR-249]
<br/>
- 백그라운드 url
=> 백그라운드 url 이미지 경로 변경 

apps/service/entities/recent-article-item/ui/RecentArticleItem.tsx, apps/service/entities/user-article/ui/ArticleView.tsx, apps/service/middleware.ts
<br/>
- [rewrites 요청 에러](https://attractorr.atlassian.net/browse/ATR-256)
<br/>
- rewrites 요청 에러 수정
- 미들웨어 matcher 에 "server" prefix 추가로 해결
<br/>
=> rewrites 요청 에러 수정

apps/service/entities/profile/ui/ProfileBackground.tsx, apps/service/entities/profile/ui/ProfileImage.tsx, apps/service/features/calendar/ui/Calendar.tsx, apps/service/features/newsletter-profile/ui/NewsletterProfile.tsx, apps/service/features/profile-container/ui/ProfileContainer.tsx, apps/service/features/set-theme/index.ts, apps/service/widgets/header/ui/Header.tsx
<br/>
- [캘린더 테마 타입에러 수정](https://attractorr.atlassian.net/browse/ATR-249)
<br/>
- 캘린더 테마 타입에러 수정
=> fix: 테마 타입 에러 수정 (#ATR-249)

apps/service/__mocks__/handlers/mypage/index.ts, apps/service/entities/news-card/ui/CardThumbnail.tsx, apps/service/entities/user-article/model/userArticleQueryKeys.ts, apps/service/features/graph/ui/Graph.tsx, apps/service/features/profile-container/ui/ProfileContainer.tsx, apps/service/features/recent-newsletter/model/type/recentNewsletter.ts, apps/service/features/recent-newsletter/ui/RecentNewsletterContainer.tsx, apps/service/widgets/inbox/ui/ArticleDetail.tsx
=> 프로덕션 배포 전 최종 수정

apps/service/app/api/auth/callback/google/route.ts, apps/service/entities/recent-article-item/ui/RecentArticleItem.tsx, apps/service/features/profile-container/ui/ProfileSettingModal.tsx, apps/service/features/recent-newsletter/ui/RecentNewsletterContainer.tsx, apps/service/shared/ui/carousel/embla.css
=>  hotfix 수정 

apps/service/__mocks__/handlers/inbox/index.ts, apps/service/entities/auth/ui/AuthButton.tsx, apps/service/entities/user-article/api/getUserArticle.ts, apps/service/entities/user-article/api/getUserArticleList.ts, apps/service/entities/user-article/api/getUserCategories.ts, apps/service/entities/user-article/api/putUserArticle.ts, apps/service/entities/user-article/model/type/article.ts, apps/service/entities/user-article/model/type/sortType.ts, apps/service/entities/user-article/model/useUserArticleMutation.ts, apps/service/features/filter-article/model/useSortType.ts, apps/service/features/filter-article/ui/SortTypeDropdownBtn.tsx, apps/service/features/scroll-tracker/ui/ScrollTracker.tsx, apps/service/next.config.mjs, apps/service/widgets/inbox/ui/UserInbox.tsx
<br/>
- [api 관련 로직 에러 처리](https://attractorr.atlassian.net/browse/ATR-238)
<br/>
- 유저 아티클 api 관련 로직 백엔드 연동 버그 수정
<br/>
=> 유저 아티클 api 관련 로직 백엔드 연동 버그 수정

apps/service/__mocks__/handlers/inbox/index.ts, apps/service/__mocks__/handlers/tools.ts, apps/service/entities/user-article/api/getUserArticleList.ts, apps/service/entities/user-article/model/type/article.ts, apps/service/features/filter-article/model/useCategory.ts, apps/service/features/filter-article/model/useSortType.ts, apps/service/features/filter-article/model/useViewType.ts, apps/service/features/filter-article/ui/CategoryDropdownBtn.tsx, apps/service/features/filter-article/ui/FilterDropdownBtn.tsx, apps/service/features/filter-article/ui/SortTypeDropdownBtn.tsx, apps/service/features/scroll-tracker/constant/maxScrollCriteria.ts, apps/service/widgets/inbox/ui/UserInbox.tsx
<br/>
- [1차 에러 검수 (스타일 및 로직)](https://attractorr.atlassian.net/browse/ATR-259)
<br/>
- 유저 아티클 상세 뷰 뷰타입 기본값 갤러리형 → 리스트형 변경 로직 추가
- 카테고리 여러개 선택 → 1개씩만 선택으로 정책 변경 반영
- 아티클 완독 기준 86% → 80% 수정
<br/>
=> 유저 아티클 페이지 1차 에러 검수 변경사항 반영

apps/service/features/sign-up/ui/UserAgreement.tsx, apps/service/features/sign-up/ui/UserInfoNicknameInput.tsx, apps/service/features/user-setting/lib/util/checkInputValid.ts, apps/service/widgets/sign-up-container/lib/hook/useSignUpFunnel.ts, apps/service/widgets/sign-up-container/lib/utils/checkSignUpFormErr.ts, apps/service/widgets/sign-up-container/ui/SignUp.tsx
<br/>
- 닉네임 입력 안했는데 다음 버튼 누르면 넘어가는 오류 해결
- 이전버튼을 눌러서 이전 화면으로 이동했는데 다음 버튼이 disabled되는 문제 해결
=> 회원가입 로직 에러 수정

apps/service/app/inbox/layout.tsx, apps/service/app/layout.tsx, apps/service/app/provider.tsx, apps/service/app/widget.tsx, apps/service/entities/auth/lib/util/AuthProvider.tsx, apps/service/entities/auth/ui/NeedLogin.tsx, apps/service/entities/auth/ui/WithAuth.tsx, apps/service/entities/news-card/ui/NewsCard.tsx, apps/service/entities/theme/lib/util/ThemeProvider.tsx, apps/service/shared/lib/util/DeviceProvider.tsx, apps/service/shared/lib/util/QueryProvider.tsx, apps/service/shared/ui/Container.tsx, apps/service/shared/ui/ContentContainer.tsx, apps/service/widgets/inbox/ui/UserInboxLayout.tsx
…TR-367)
<br/>
- [프로바이더 컨텍스트 헬 리팩토링](https://attractorr.atlassian.net/browse/ATR-367)
<br/>
- provider context hell 코드 수정 
- props with children 타입 적용
<br/>
=> provider context hell 코드 수정 및 props with children 타입 적용

apps/service/widgets/user-rank/ui/UserRank.tsx, apps/service/widgets/user-rank/ui/UserRankContent.tsx
<br/>
- [suspense 추가 및 에러 바운더리 추가](https://attractorr.atlassian.net/browse/ATR-369)
<br/>
- suspense 추가 및 에러 바운더리 추가
<br/>
=> feat: suspesne 추가 및 에러 바운더리 추가 

package.json, packages/design-system/tsconfig.json, packages/icons/package.json, packages/icons/src/index.ts, packages/icons/tsconfig.json, packages/icons/tsup.config.ts, pnpm-lock.yaml
<br/>
-
<br/>
- tsup 번들러를 사용하여 icons 패키지를 경량화하여 패키지의 성능 개선
<br/>
=> icons 패키지 tsup 번들링 적용

apps/service/features/user-setting/ui/modal/UserSettingItem.tsx
<br/>
-  개인설정 페이지 오류 해결 및 반응형 수정
<br/>
-  개인설정 페이지 오류 해결 및 반응형 수정
<br/>
-
<br/>
=> fix: 개인설정 페이지 오류 해결 및 반응형 수정 (#ATR-312)

apps/service/features/calendar/constant/calendarTheme.ts, apps/service/features/calendar/ui/Calendar.tsx, apps/service/features/recent-newsletter/ui/RecentNewsletterContainer.tsx, apps/service/features/subscribe-list/ui/SubscribeList.tsx, apps/service/widgets/user-record/ui/UserRecord.tsx
<br/>
- [mypage useAuth로 리팩토링](https://attractorr.atlassian.net/browse/ATR-455)
<br/>
- mypage useAuth로 리팩토링
=>  mypage useAuth 적용 

apps/service/app/newsletter/[newsletterId]/article/[articleId]/page.tsx, apps/service/app/newsletter/[newsletterId]/page.tsx, apps/service/widgets/newsletter-introduce/ui/NewsletterProfile.tsx
<br/>
-
<br/>
- 뉴스레터 소개, 과거 아티클 페이지 revalidate time 지정
- 뉴스레터 소개 페이지에서 링크가 잘못 연결되어있던 문제 수정 (홈페이지로 이동)
<br/>
=> 뉴스레터 소개, 과거 아티클 페이지 revalite time 지정

apps/service/entities/theme/constant/index.ts, apps/service/entities/theme/constant/theme-list.ts, apps/service/entities/theme/constant/themeList.ts, apps/service/entities/theme/constant/themeName.ts, apps/service/entities/theme/model/type/theme.ts, apps/service/entities/theme/ui/ThemeDropdownBtn.tsx, apps/service/features/user-setting/lib/hook/index.ts, apps/service/features/user-setting/lib/hook/useModal.ts, apps/service/features/user-setting/lib/index.ts, apps/service/features/user-setting/lib/util/checkInputValid.ts, apps/service/features/user-setting/lib/util/checkUserSettingInputError.ts, apps/service/features/user-setting/lib/util/index.ts, apps/service/features/user-setting/model/index.ts, apps/service/features/user-setting/ui/UserInfoGeneral.tsx, apps/service/features/user-setting/ui/UserInfoNotification.tsx, apps/service/features/user-setting/ui/UserInfoSetting.tsx, apps/service/features/user-setting/ui/UserInfoWithdraw.tsx, apps/service/features/user-setting/ui/modal/UserSettingExpirationDateModal.tsx, apps/service/features/user-setting/ui/modal/UserSettingInterestModal.tsx, apps/service/features/user-setting/ui/modal/UserSettingItem.tsx, apps/service/features/user-setting/ui/modal/UserSettingJobModal.tsx, apps/service/features/user-setting/ui/modal/UserSettingModal.tsx, apps/service/features/user-setting/ui/modal/UserSettingNicknameModal.tsx, apps/service/features/user-setting/ui/modal/UserSettingThemeModal.tsx
<br/>
- [스타일 검수](https://attractorr.atlassian.net/browse/ATR-410)
<br/>
- 개인설정 페이지 스타일 검수
- 테마 이름 통합
<br/>
=> 개인설정 페이지 스타일 검수 및 테마 이름 통합

packages/design-system/src/DIalog/Dialog.tsx, packages/design-system/src/Drawer/Drawer.tsx
<br/>
- [dialog 및 drawer 컴포넌트 스타일 수정](https://attractorr.atlassian.net/browse/ATR-484)
<br/>
- dialog 및 drawer 컴포넌트 스타일 수정
<br/>
=> dialog 및 drawer 컴포넌트 스타일 수정 (DS)

apps/service/features/user-setting/ui/modal/UserSettingExpirationDateModal.tsx
<br/>
- [배포 오류 해결](https://attractorr.atlassian.net/browse/ATR-482)
<br/>
- 배포 오류 해결
=> fix: 유저 개인정보 만료 버그 픽스 (#ATR-482)

.github/workflows/chromatic_workflow.yml, .github/workflows/workflow.yml, package.json, packages/design-system/package.json, packages/design-system/src/Dialog/Dialog.stories.tsx, pnpm-lock.yaml
<br/>
-
<br/>
- 스토리북 크로마틱 배포
- 기존 메인 ci로직에 불필요한 내용 삭제
- 스토리북 ci로직 추가
<br/>
=> 스토리북 크로마틱 배포

apps/service/src/app/api/auth/callback/google/route.ts, apps/service/src/features/subscribe-newsletter/api/subscribeNewsletter.ts, apps/service/src/features/subscribe-newsletter/model/subscribeNewsletterKeys.ts, apps/service/src/features/subscribe-newsletter/model/type/subscribeNewsletter.ts, apps/service/src/features/subscribe-newsletter/model/useSubscribeNewsletter.ts, apps/service/src/features/subscribe-newsletter/ui/AutoSubscribeConfirm.tsx, apps/service/src/features/subscribe-newsletter/ui/UnsubscribeConfirm.tsx, apps/service/src/features/subscribe-newsletter/ui/UserSubscribeButton.tsx
<br/>
- [[FE] 구독 취소](https://attractorr.atlassian.net/browse/ATR-563)
- [세션 아이디 쿠키 설정 변경](https://attractorr.atlassian.net/browse/ATR-553)
<br/>
- 뉴스레터 구독 취소 기능 추가
- 세션 아이디 쿠키 설정 SameSite=Strict 로 변경
<br/>
=> 구독 취소 기능 추가 및 세션아이디 쿠키 설정 변경

.eslintrc.cjs, package.json, packages/icons/package.json, pnpm-lock.yaml
=> ci 환경에서 prettier 에러 수정

.eslintrc.cjs, .github/workflows/workflow.yml, apps/service/.eslintrc.cjs, apps/service/src/features/profile-container/model/type/settingForm.ts, packages/design-system/packages/core/.eslintrc.cjs, packages/design-system/packages/core/src/components/button/Button.stories.tsx, packages/design-system/packages/core/src/components/button/Button.style.ts, packages/design-system/packages/core/src/components/button/Button.tsx, packages/design-system/packages/core/src/components/button/_index.scss, packages/design-system/packages/core/src/components/dialog/Dialog.util.ts, packages/design-system/packages/core/src/components/input-description/_index.scss, packages/design-system/packages/core/src/components/search-input/SearchInput.stories.tsx, packages/design-system/packages/core/src/components/search-input/SearchInput.style.ts, packages/design-system/packages/core/src/components/search-input/SearchInput.tsx, packages/design-system/packages/core/src/components/search-input/_index.scss, packages/design-system/packages/core/src/components/select/Select.constant.ts, packages/design-system/packages/core/src/components/select/Select.stories.tsx, packages/design-system/packages/core/src/components/select/Select.style.ts, packages/design-system/packages/core/src/components/select/Select.tsx, packages/design-system/packages/core/src/components/select/Select.type.ts, packages/design-system/packages/core/src/components/select/Select.util.ts, packages/design-system/packages/core/src/components/select/_index.scss, packages/design-system/packages/core/src/components/text-input/TextInput.stories.tsx, packages/design-system/packages/core/src/components/text-input/TextInput.style.ts, packages/design-system/packages/core/src/components/text-input/TextInput.tsx, packages/design-system/packages/core/src/components/text-input/_index.scss, packages/design-system/packages/core/src/core/types/focusableElement.ts, packages/design-system/packages/core/src/core/types/index.ts, packages/design-system/packages/core/src/core/utils/getFocusableElement.ts, packages/design-system/packages/core/src/core/utils/index.ts
<br/>
- [[FE] 디자인 시스템](https://attractorr.atlassian.net/browse/ATR-604)
- [패키지 설정](https://attractorr.atlassian.net/browse/ATR-605)
- [컴포넌트 작업](https://attractorr.atlassian.net/browse/ATR-606)
<br/>
- import 관련 린트 룰 변경
- 인풋 컴포넌트 사이즈 옵션 확장
<br/>
=> 디자인 시스템 구축 (3차)
